baseurl = "/"
languageCode = "nl-NL"
title = "Nederlandse hackerspaces en -organisaties"
paginate = 5
theme = "hsnl"

enableRobotsTXT = true
googleAnalytics = ""
disqusShortname = ""
SectionPagesMenu = "main"
canonifyURLs = true

[params]
  description="work in progress"
  powered_by = ""
  hide_author = false
  images = []
  github = ""
  twitter = ""
  author = "HSNL"
  copyright = "Copy?"
  avatar = "css/images/avatar.png"
  logo = "css/images/logo.png"
  date_format = "January 02, 2006"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Contact"
  url = "/contact"
  weight = 2